language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - sed -i 's/TRACKER_TOKEN/'"$TRACKER_TOKEN"'/g' config.yml

script:
  - pytest
  - behave features

branches:
  only:
    - develop
