language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - pytest
  - behave features

branches:
  only:
    - develop

env:
  global:
    - token=$TRACKER_TOKEN

